### ISSUE TITLE
No automatic RDS backups enabled

### ISSUE THREAD

**Issue by analytically** [EngineerBetter/concourse-up#20]

**Comment by bruxelles86** [comment]
Hi.

Although enabling the auto-generation of RDS snapshots is fairly trivial, we don't do this because restoring from those snapshots in the event of a disaster would be very awkward. Getting your Concourse deployment to talk to the new RDS instance would require (I think) making manual changes to the manifest, and if you ever wanted to use Concourse-up with that deployment again you'd also need to doctor the tfstate.

We've currently got a story in flight to introduce a backup mechanism, and right now it looks likely that that will make use of a tool called (BOSH Backup and Restore)[https://github.com/cloudfoundry-incubator/bosh-backup-and-restore].
