### ISSUE TITLE
deploy fails on installing CPI

### ISSUE THREAD

**Issue by tomdavidson** [EngineerBetter/concourse-up#55]
version 0.10.4

```
Started installing CPI
  Compiling package 'ruby-2.4-r4/0cdc60ed7fdb326e605479e9275346200af30a25'... Failed (00:01:14)
Failed installing CPI (00:01:14)

Installing CPI:
  Compiling job package dependencies for installation:
    Compiling job package dependencies:
      Compiling package:
        Running command: 'bash -x packaging', stdout: 'checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes

... 3k lines ...

	from setup.rb:46:in `<main>'
+ echo 'Cannot install rubygems'
+ exit 1
':
          exit status 1

Exit code 1
exit status 1

```

**Comment by peterellisjones** [comment]
Hi Tom,

This is saying rubygems cannot be installed on your local machine. Under the hood, concourse-up uses [bosh create-env](https://bosh.io/docs/init/) to bootstrap the BOSH director on AWS. This requires running a _local_ copy of the bosh director (essentially, the bosh director for the bosh director), which means running some Ruby. To do that it first compiles and installs Ruby and the error is saying that this failed. Typically this is due to libraries such as libyaml, or tools such as gcc or make not being available on your local machine. 

I would start by making sure you have the dependencies listed here for your OS installed and seeing if this fixes the issue:

https://bosh.io/docs/cli-v2-install/#additional-dependencies

**Comment by tomdavidson** [comment]
Now I remember I am on a new machine :D 

Thank you for the uber quick response - I did not even realize so much of that work was being done local.
