### ISSUE TITLE
Windows file does not exist error

### ISSUE THREAD

**Issue by jwenz723** [EngineerBetter/concourse-up#85]
1. I downloaded the 0.18.1 [concourse-up-windows-amd64.exe](https://github.com/EngineerBetter/concourse-up/releases/download/0.18.1/concourse-up-windows-amd64.exe) from the github releases page.
2. I set my AWS credentials, tried both of the following methods:
    - environment variables (AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY)
    - ~/.aws/credentials file with [default]
3. I ran `concourse-up deploy jeff`
4. Got the following output:
```
WARNING: allowing access from local machine (address: xx.xxx.xx.x)

exec: "C:\\Users\\jeff.wenzbauer\\AppData\\Local\\concourse-up\\bin\\6247773d6fdf8f4425f13af43250c8af676285c53cfa9a161f19fa3046a2c7b0": file does not exist
```

When I follow the same steps on a linux machine everything works as expected with no error.

**Comment by crsimmons** [comment]
We don't test the windows binary _at all_ nor do we really expect it to work since `bosh create-env` doesn't work on windows.

We never used to publish windows binaries but someone asked us to in https://github.com/EngineerBetter/concourse-up/issues/22

I see we don't have it written in the README or release notes that it is not supported/won't work. I'll make a story in our backlog to add that.

**Comment by jwenz723** [comment]
Ok. Thanks for the info. 

I think a mention in the README would be great, so other people don't go crazy trying to figure out why it doesn't run!
